import React from 'react'
import { AvatarDescriptor, genderOf, seedOf } from '../../../types/Avatar'
import { avatarColours } from './spriteFactory'
import { seededRandom, shade } from './palette'

const GRID = 12

type Cell = { x: number; y: number; fill: string }

const rgb = (c: [number, number, number]) => `rgb(${c[0]},${c[1]},${c[2]})`

/**
 * A small 8-bit bust drawn as SVG rects, from the same seed as the world
 * sprite, so the two read as the same character. Nothing is fetched and
 * nothing is generated by a model - it is a handful of rectangles.
 */
export function Portrait({ avatar, size = 64 }: { avatar: AvatarDescriptor; size?: number }) {
  const colours = avatarColours(avatar)
  const gender = genderOf(avatar)
  // folded into the seed so switching gender visibly changes the preview, the
  // way it changes which drawn character the world sprite is built from
  const random = seededRandom((seedOf(avatar) ^ 0x5bf03635) + gender.charCodeAt(0))

  const skin = shade(colours.skin, 1)
  const skinShadow = shade(colours.skin, 0.86)
  const hair = shade(colours.hair, 1)
  const hairShadow = shade(colours.hair, 0.78)
  const top = shade(colours.top, 1)
  const outline = [58, 58, 80] as [number, number, number]

  // a few silhouettes rather than one, so faces are not all the same shape
  const style = Math.floor(random() * 3)
  // Definite rather than likely: leaving this to chance meant a feminine and a
  // masculine avatar on the same seed sometimes came out identical, which makes
  // the gender control look broken. Variety comes from style and colour instead.
  const longHair = gender === 'f' ? true : gender === 'm' ? false : random() < 0.5

  const cells: Cell[] = []
  const put = (x: number, y: number, fill: string) => {
    if (x < 0 || y < 0 || x >= GRID || y >= GRID) return
    cells.push({ x, y, fill })
  }

  // shoulders
  for (let x = 1; x <= 10; x++) for (let y = 9; y <= 11; y++) put(x, y, rgb(top))
  for (let x = 1; x <= 10; x++) put(x, 9, rgb(shade(colours.top, 1.15)))

  // neck
  for (let x = 5; x <= 6; x++) put(x, 8, rgb(skinShadow))

  // face
  for (let x = 3; x <= 8; x++) for (let y = 3; y <= 8; y++) put(x, y, rgb(skin))
  for (let y = 3; y <= 8; y++) { put(3, y, rgb(skinShadow)); put(8, y, rgb(skinShadow)) }

  // hair: a cap over the top, optionally falling past the jaw
  for (let x = 2; x <= 9; x++) for (let y = 1; y <= 2; y++) put(x, y, rgb(hair))
  for (let x = 3; x <= 8; x++) put(x, 3, rgb(style === 0 ? hair : hairShadow))
  put(2, 3, rgb(hair)); put(9, 3, rgb(hair))
  if (longHair) {
    for (let y = 4; y <= 7; y++) { put(2, y, rgb(hairShadow)); put(9, y, rgb(hairShadow)) }
  }
  if (style === 1) for (let x = 4; x <= 7; x++) put(x, 3, rgb(hair)) // fringe

  // eyes and mouth stay dark, the way the sprites draw them
  put(4, 5, rgb(outline))
  put(7, 5, rgb(outline))
  put(5, 7, rgb(skinShadow))
  put(6, 7, rgb(skinShadow))

  return (
    <svg
      width={size}
      height={size}
      viewBox={`0 0 ${GRID} ${GRID}`}
      shapeRendering="crispEdges"
      role="img"
      aria-label="avatar"
    >
      <rect width={GRID} height={GRID} fill="rgba(0,0,0,0.18)" rx="1" />
      {cells.map((cell, index) => (
        <rect key={index} x={cell.x} y={cell.y} width="1" height="1" fill={cell.fill} />
      ))}
    </svg>
  )
}
